---
# Official build is on https://readthedocs.org/projects/tango-controls/ (triggered via webhook)
# but we test doc generation in the pipeline

pre-commit:
  image: registry.gitlab.com/tango-controls/docker/pre-commit:3.7.0-2
  tags:
    - docker, linux, amd64
  variables:
    PRE_COMMIT_HOME: ${CI_PROJECT_DIR}/.cache/pre-commit
  script:
    - pre-commit run --all-files --show-diff-on-failure
  cache:
    key: pre-commit-cache
    paths:
      - ${PRE_COMMIT_HOME}

test-docs:
  image: ghcr.io/sphinx-doc/sphinx:8.1.3
  tags: [linux, docker, amd64]
  needs:
    - pre-commit
  before_script:
    - python -m pip install -r requirements.txt
  script:
    - make html
    - echo "Documentation can be found at https://$CI_PROJECT_NAMESPACE.gitlab.io/-/$CI_PROJECT_NAME/-/jobs/$CI_JOB_ID/artifacts/build/html/index.html"
  artifacts:
    when: always
    paths:
      - sphinx-output.log
      - build
  environment:
    name: Docs-dev
    url: "https://$CI_PROJECT_NAMESPACE.gitlab.io/-/$CI_PROJECT_NAME/-/jobs/$CI_JOB_ID/artifacts/build/html/index.html"
