---
# Official build is on https://readthedocs.org/projects/tango-controls/ (triggered via webhook)
# but we test doc generation in the pipeline
test-docs:
  stage: test
  image: ghcr.io/sphinx-doc/sphinx:8.1.3
  tags: [linux, docker, amd64]
  before_script:
    - python -m pip install -r requirements.txt
  script:
    - sphinx-build -w sphinx-output.log ./source build
    - echo "Documentation can be found at https://$CI_PROJECT_NAMESPACE.gitlab.io/-/$CI_PROJECT_NAME/-/jobs/$CI_JOB_ID/artifacts/build/index.html"
  artifacts:
    when: always
    paths:
      - sphinx-output.log
      - build
  environment:
    name: Docs-dev
    url: "https://$CI_PROJECT_NAMESPACE.gitlab.io/-/$CI_PROJECT_NAME/-/jobs/$CI_JOB_ID/artifacts/build/index.html"
